import os #IMPORTING THE OS MODULE (this is single-line comment)
#THIS PROGRAM IS TO PRINT HELLO WORLD
'''THIS PROGRAM IS WRIITEN BY JAINIL PATEL
HE IS LEARNING PYTHON THROUGH CODE WITH HARRY'''
print("HELLO WORLD")